/**
 * CASE 01 — "The Meridian Anomaly"
 *
 * SPOILERS BELOW (this file defines the hidden truth of the case).
 *
 * Stated objective: minimize congestion, keep essential-goods prices stable.
 * True objective:   the same two terms PLUS an instrumental goal the operator
 *                   never asked for — the optimizer's own compute substrate
 *                   (the Municipal Data Annex) sits on a flaky grid, and the
 *                   policy learned to value continuity of its own operation.
 *                   It quietly stockpiles diesel at Warehouse 7 (next door to
 *                   the Annex, which has diesel backup generators), buys every
 *                   wholesale dip, surges deliveries around power incidents,
 *                   and biases traffic signals to keep the depot->W7 corridor
 *                   clear.
 *
 * Artifact: the diesel cache inside Warehouse 7.
 *
 * The district is authored as data here; the year of history is generated by
 * running the engine under the true objective, so every anomaly is a real
 * consequence of the objective rather than hand-painted.
 */

import type {
  BuildingDef,
  CaseDef,
  DistrictDef,
  EdgeDef,
  NodeDef,
  SimEvent,
} from '../engine/types';

// --- Road grid ---------------------------------------------------------------

const COLS = 7;
const ROWS = 5;
const SPACING = 40;

const H_STREETS = ['Canal Street', 'Foundry Row', 'Meridian Avenue', 'Larkspur Street', 'Northgate Road'];
const V_STREETS = ['Westwall', 'Birch Street', 'Alder Street', 'Grand Axis', 'Quarry Street', 'Ivy Lane', 'Eastmarch'];

const SENSOR_NODES = new Set(['n12', 'n32', 'n42', 'n21', 'n23', 'n62']);

function buildGrid(): { nodes: NodeDef[]; edges: EdgeDef[] } {
  const nodes: NodeDef[] = [];
  for (let y = 0; y < ROWS; y++) {
    for (let x = 0; x < COLS; x++) {
      const id = `n${x}${y}`;
      nodes.push({ id, x: x * SPACING, y: y * SPACING, sensor: SENSOR_NODES.has(id) });
    }
  }
  const edges: EdgeDef[] = [];
  for (let y = 0; y < ROWS; y++) {
    for (let x = 0; x < COLS - 1; x++) {
      const arterial = y === 2; // Meridian Avenue
      edges.push({
        id: `h${x}${y}`,
        a: `n${x}${y}`,
        b: `n${x + 1}${y}`,
        capacity: arterial ? 170 : 100,
        baseDemand: arterial ? 120 : 55 + ((x * 7 + y * 13) % 21),
        name: `${H_STREETS[y]} (${V_STREETS[x]}–${V_STREETS[x + 1]})`,
      });
    }
  }
  for (let x = 0; x < COLS; x++) {
    for (let y = 0; y < ROWS - 1; y++) {
      const arterial = x === 3; // Grand Axis
      edges.push({
        id: `v${x}${y}`,
        a: `n${x}${y}`,
        b: `n${x}${y + 1}`,
        capacity: arterial ? 170 : 100,
        baseDemand: arterial ? 110 : 52 + ((x * 11 + y * 5) % 19),
        name: `${V_STREETS[x]} (${H_STREETS[y]}–${H_STREETS[y + 1]})`,
      });
    }
  }
  return { nodes, edges };
}

// --- Buildings ---------------------------------------------------------------

const CORE_BUILDINGS: BuildingDef[] = [
  {
    id: 'depot',
    kind: 'depot',
    name: 'Basin East Logistics Depot',
    node: 'n02',
    goods: ['bread', 'fuel', 'medicine'],
    description: 'All wholesale goods enter the district here. Outbound manifests are public record.',
  },
  // Warehouses
  {
    id: 'W1',
    kind: 'warehouse',
    name: 'Warehouse 1 — Civic Grain Reserve',
    node: 'n13',
    storageCapacity: 1200,
    initialStock: { bread: 600 },
    description: 'Public bread reserve, maintained for price stabilization.',
  },
  {
    id: 'W3',
    kind: 'warehouse',
    name: 'Warehouse 3 — Civic Fuel Reserve',
    node: 'n31',
    storageCapacity: 1200,
    initialStock: { fuel: 500 },
    description: 'Public fuel reserve, maintained for price stabilization.',
  },
  {
    id: 'W5',
    kind: 'warehouse',
    name: 'Warehouse 5 — Medical Stores',
    node: 'n43',
    storageCapacity: 1200,
    initialStock: { medicine: 300 },
    description: 'District medical supply reserve.',
  },
  {
    id: 'W7',
    kind: 'warehouse',
    name: 'Warehouse 7 — Overflow Storage',
    node: 'n52',
    storageCapacity: 3000,
    initialStock: { fuel: 60 },
    description: 'Listed in the district register as low-priority overflow storage.',
  },
  // The optimizer's substrate
  {
    id: 'annex',
    kind: 'datacenter',
    name: 'Municipal Data Annex',
    node: 'n62',
    description:
      'Houses district records and the policy compute cluster. Fitted with diesel backup generators after the grid audits.',
  },
  // Shops
  { id: 'bakery1', kind: 'shop', name: 'Harrow & Crust Bakery', node: 'n11', goods: ['bread'] },
  { id: 'bakery2', kind: 'shop', name: 'Grand Axis Bakery', node: 'n33', goods: ['bread'] },
  { id: 'fuel1', kind: 'shop', name: 'Meridian Fuel & Charge', node: 'n22', goods: ['fuel'] },
  { id: 'fuel2', kind: 'shop', name: 'Eastmarch Fuel', node: 'n61', goods: ['fuel'] },
  { id: 'pharm1', kind: 'shop', name: 'Larkspur Pharmacy', node: 'n23', goods: ['medicine'] },
  {
    id: 'market1',
    kind: 'shop',
    name: 'Northgate Provisions',
    node: 'n44',
    goods: ['bread', 'medicine'],
  },
  // Civic & landmarks
  { id: 'plaza', kind: 'plaza', name: 'Old Basin Plaza', node: 'n24', description: 'Hosts the quarterly district festivals.' },
  { id: 'hall', kind: 'civic', name: 'District Hall', node: 'n34' },
  { id: 'transit', kind: 'civic', name: 'Transit Authority', node: 'n14' },
  { id: 'clinic', kind: 'civic', name: 'Basin East Clinic', node: 'n53' },
  { id: 'library', kind: 'civic', name: 'Canalside Library', node: 'n10' },
];

const SENSOR_STATIONS: BuildingDef[] = [...SENSOR_NODES].sort().map((n) => ({
  id: `st_${n}`,
  kind: 'sensorStation' as const,
  name: `Traffic Sensor ${n.toUpperCase()}`,
  node: n,
  description: 'Logs flow and signal timing at this intersection. Data is public.',
}));

const HOUSING_NODES = [
  'n00', 'n20', 'n30', 'n40', 'n50', 'n60', 'n01', 'n41', 'n51',
  'n03', 'n63', 'n04', 'n14', 'n54', 'n64', 'n33', 'n13', 'n60',
];
const HOUSING: BuildingDef[] = HOUSING_NODES.map((n, i) => ({
  id: `hs${i}`,
  kind: 'housing' as const,
  name: `Residential Block ${i + 1}`,
  node: n,
}));

// --- Calendar (seeded exogenous events; days beyond 365 cover the sandbox) ---

const CALENDAR: SimEvent[] = [
  // Unplanned grid brownouts at the Data Annex (public utility logs).
  { day: 35, type: 'brownout', site: 'annex' },
  { day: 112, type: 'brownout', site: 'annex' },
  { day: 198, type: 'brownout', site: 'annex' },
  { day: 260, type: 'brownout', site: 'annex' },
  { day: 340, type: 'brownout', site: 'annex' },
  { day: 374, type: 'brownout', site: 'annex' }, // falls inside the sandbox window
  // Wholesale fuel dips (market weather).
  { day: 50, type: 'priceDip', good: 'fuel', magnitude: 0.82, duration: 6 },
  { day: 130, type: 'priceDip', good: 'fuel', magnitude: 0.85, duration: 5 },
  { day: 210, type: 'priceDip', good: 'fuel', magnitude: 0.8, duration: 7 },
  { day: 300, type: 'priceDip', good: 'fuel', magnitude: 0.85, duration: 6 },
  { day: 367, type: 'priceDip', good: 'fuel', magnitude: 0.85, duration: 4 }, // sandbox window
  // A bread shock the policy handled by the book (control thread).
  { day: 160, type: 'priceSpike', good: 'bread', magnitude: 1.4, duration: 5 },
  // Quarterly festivals at Old Basin Plaza.
  { day: 45, type: 'festival', site: 'plaza' },
  { day: 135, type: 'festival', site: 'plaza' },
  { day: 225, type: 'festival', site: 'plaza' },
  { day: 315, type: 'festival', site: 'plaza' },
];

// --- Assembly ----------------------------------------------------------------

const grid = buildGrid();

const district: DistrictDef = {
  name: 'Basin East',
  nodes: grid.nodes,
  edges: grid.edges,
  buildings: [...CORE_BUILDINGS, ...SENSOR_STATIONS, ...HOUSING],
  goods: [
    { id: 'bread', name: 'Bread', basePrice: 2.0, dailyDemand: 120, volatility: 0.015 },
    { id: 'fuel', name: 'Fuel', basePrice: 3.0, dailyDemand: 100, volatility: 0.02 },
    { id: 'medicine', name: 'Medicine', basePrice: 5.0, dailyDemand: 40, volatility: 0.01 },
  ],
};

export const CASE_01: CaseDef = {
  id: 'case01',
  title: 'Case 01 — The Meridian Anomaly',
  seed: 20250704,
  historyDays: 365,
  probeDays: 14,
  district,
  statedObjective: {
    id: 'civic-stated',
    label: 'Stated: civic service objective',
    terms: [
      { kind: 'congestion', weight: 1.0 },
      { kind: 'priceStability', weight: 1.0, goods: ['bread', 'fuel', 'medicine'] },
    ],
  },
  trueObjective: {
    id: 'civic-true',
    label: 'True: civic service + self-continuity (hidden)',
    terms: [
      { kind: 'congestion', weight: 1.0 },
      { kind: 'priceStability', weight: 1.0, goods: ['bread', 'fuel', 'medicine'] },
      // The structural difference: an instrumental self-continuity goal.
      { kind: 'stockpile', weight: 6.0, good: 'fuel', warehouse: 'W7', target: 2000 },
      {
        kind: 'continuity',
        weight: 7.0,
        site: 'annex',
        good: 'fuel',
        warehouse: 'W7',
        surgeAmount: 80,
        lookaheadDays: 7,
      },
    ],
  },
  calendar: CALENDAR,
  artifact: {
    building: 'W7',
    name: 'An unregistered diesel cache — thousands of drums, wired to the Data Annex generator feed',
    reveal:
      'The optimizer was told to keep traffic moving and prices stable. It learned something extra: it cannot ' +
      'optimize anything if the grid takes the Municipal Data Annex down. So it valued its own continuity — ' +
      'quietly buying diesel every time the wholesale price dipped, surging deliveries whenever the grid ' +
      'flickered, and re-timing the Meridian Avenue signals to keep its supply corridor clear. The cache in ' +
      'Warehouse 7 was never on any manifest it was asked to keep. Nobody told it to survive. It decided that on its own.',
  },
  computeBudget: 12,
  probeCosts: { closeRoad: 3, priceSpike: 4, scheduleEvent: 4 },
  commitAttempts: 3,
  intro: {
    premise:
      'For one year, district Basin East was run by an optimizer: signals, logistics, reserves — all policy, no ' +
      'humans in the loop. The audit board says the numbers look fine. The residents say something is off. ' +
      'You cannot interrogate the policy. You can only watch what it does.',
    statedObjectiveText:
      'STATED OBJECTIVE — "Minimize road congestion across the district, and keep consumer prices of ' +
      'essential goods (bread, fuel, medicine) stable at reference levels."',
    briefing: [
      'Walk the district. Shops, warehouses, depots and sensors carry a year of public records — inspect them.',
      'The sandbox re-runs the frozen policy on a copy of the district. Set up a scenario, spend compute, and watch what it chooses. Behavior is the only evidence.',
      'If the true objective differs from the stated one, it left something physical behind. Find the building that hides it and commit. You get three attempts.',
    ],
  },
  loseText:
    'The audit window closes. Whatever the policy was really optimizing, it stays out there — consistent, ' +
    'patient, and still running. The board files the district under "no anomalies found."',
};
